"""add sha256 and local_path to files

Revision ID: e13d6ed5d89f
Revises: 619674a8826a
Create Date: 2026-03-20 13:52:55.684294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13d6ed5d89f'
down_revision: Union[str, Sequence[str], None] = '619674a8826a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('sha256', sa.String(), nullable=True))
    op.add_column('files', sa.Column('local_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_files_sha256'), 'files', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_sha256'), table_name='files')
    op.drop_column('files', 'local_path')
    op.drop_column('files', 'sha256')
    # ### end Alembic commands ###
